### ISSUE TITLE
getStats returns empty in case for firefox.

### ISSUE THREAD

**Issue by karthikbr82** [aws/connect-rtc-js#46] opened 2019-05-09 12:34 UTC
getStats returns empty in case for firefox.

Problem is because of the webrtc-adapter, The version of webrtc-adapter supported is very old and it causes this issue.

**Comment by dnovicki** [comment] 2019-05-09 16:05
+1 May be time to update

Connect team: what browsers is connect-rtc-js supporting?

**Comment by karthikbr82** [comment] 2019-05-10 07:34
@dnovicki As per the documentation
https://docs.aws.amazon.com/connect/latest/adminguide/what-is-amazon-connect.html#browsers

<img width="778" alt="Screenshot 2019-05-10 at 10 33 19" src="https://user-images.githubusercontent.com/12692403/57510349-3b69bd80-730f-11e9-8f5e-81f17cba4faa.png">

**Comment by yiming-amzn** [comment] 2023-03-02 17:07
the issue is resolved by https://github.com/aws/connect-rtc-js/pull/50

**Closed by yiming-amzn** 2023-03-02 17:07 UTC
