### ISSUE TITLE
connect-rtc-js is broken in Chrome Beta 74

### ISSUE THREAD

**Issue by supercycle91** [aws/connect-rtc-js#45] opened 2019-03-28 00:00 UTC
https://www.chromestatus.com/features#milestone%3D74

Unsure what changes are breaking ATM.

Here is my error: 
<img width="1340" alt="Screen Shot 2019-03-27 at 4 54 57 PM" src="https://user-images.githubusercontent.com/10945176/55120083-bbb2c700-50b1-11e9-8d65-b6c55c0a177e.png">

Steps to reproduce:
1. Download Canary 75 or Beta 74 of Chrome
2. Receive/make a call and see failure in console

**Comment by karthikbr82** [comment] 2019-03-28 09:01
@supercycle91 are you seeing the same behavior as reported in the issue44 - https://github.com/aws/connect-rtc-js/issues/44

**Comment by pallab-gain** [comment] 2019-03-28 11:54
In my tests with M74 -
The [iceConnectionState](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/iceConnectionState) never comes to `completed` in M74. ICE state goes to `closed` from `connected`. It's more of a WebRTC issue due to incompatible changes (with connect rtc media server) in M74 release. I think, it is different than #44 , and not a WebSocket issue.

[WebRTC M74 Release Notes](https://groups.google.com/forum/#!topic/discuss-webrtc/cXEtXIIYrQs)

**Comment by jossulli** [comment] 2019-03-28 14:39
Thanks for reporting this, we're looking into now.

**Comment by yuliangz** [comment] 2019-04-02 14:56
It's related to Chrome's plan to remove DTLS1.0 support. See https://bugs.chromium.org/p/webrtc/issues/detail?id=10261
The change is reverted now. 74/75 should be good as soon as the change is released. We will plan for DTLS1.2 upgrade

**Comment by yuliangz** [comment] 2019-04-08 20:04
Verified the issue is fixed in 74.0.3729.61

**Closed by yuliangz** 2019-04-08 20:04 UTC
