### ISSUE TITLE
getStats throwing error on Chrome canary 75

### ISSUE THREAD

**Issue by karthikbr82** [aws/connect-rtc-js#44] opened 2019-03-27 08:47 UTC
There is an issue with getStats call when used with chrome canary 75 (latest release).
The Error "Agent Hung up" shows up in the ccp and in the console logs this error is found

`lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38975 Uncaught (in promise) TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': parameter 2 is not of type 'MediaStreamTrack'.
    at lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38975
    at new Promise (<anonymous>)
    at RTCPeerConnection.pc.getStats (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38973)
    at RtcSession._callee$ (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42244)
    at tryCatch (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37351)
    at Generator.invoke [as _invoke] (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37585)
    at Generator.prototype.<computed> [as next] (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37403)
    at step (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35209)
    at lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35227
    at new Promise (<anonymous>)
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38975
pc.getStats @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38973
_callee$ @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42244
tryCatch @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37351
invoke @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37585
prototype.<computed> @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37403
step @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35209
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35227
F @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35622
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35206
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42269
_callee2$ @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42236
tryCatch @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37351
invoke @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37585
prototype.<computed> @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37403
step @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35209
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35227
F @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35622
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35206
impl @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42285
_callee3$ @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42295
tryCatch @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37351
invoke @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37585
prototype.<computed> @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37403
step @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35209
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35227
F @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35622
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35206
getStats @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42366
getUserAudioStats @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42399
(anonymous) @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:34419
setInterval (async)
startStatsCollectionJob @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:34418
session.onSessionConnected @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:34094
onEnter @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:41823
transit @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42090
transit @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:41319
_checkAndTransit @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:41793
onSignalingHandshaked @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:41787
_signalingHandshaked @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42126
_hitchedFunction @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:44338
notifyHandshaked @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:43881
onEnter @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:43880
transit @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:44132
transit @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:43555
onRpcMsg @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:43855
_onMessage @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:44172
_hitchedFunction @ lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:44338
lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38975 Uncaught (in promise) TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': parameter 2 is not of type 'MediaStreamTrack'.
    at lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38975
    at new Promise (<anonymous>)
    at RTCPeerConnection.pc.getStats (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:38973)
    at RtcSession._callee$ (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:42244)
    at tryCatch (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37351)
    at Generator.invoke [as _invoke] (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37585)
    at Generator.prototype.<computed> [as next] (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:37403)
    at step (lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35209)
    at lily_ccp_Prod_bc63a5c4a9c6a630bee59e97eb483bd52f057cf6.gz.js:35227
    at new Promise (<anonymous>)

<img width="326" alt="Screenshot 2019-03-27 at 10 44 09" src="https://user-images.githubusercontent.com/12692403/55061902-89877200-507d-11e9-89bc-f7f56c22cbf5.png">
<img width="1371" alt="Screenshot 2019-03-27 at 10 43 59" src="https://user-images.githubusercontent.com/12692403/55061910-8db38f80-507d-11e9-977f-2614643703c0.png">

`

**Comment by jossulli** [comment] 2019-03-28 14:41
Thanks for reporting, resolving as a duplicate of #45

**Comment by karthikbr82** [comment] 2019-04-02 12:45
@jossulli Its not the same issue as #45 , #45 is related to iceConnectionState and this issue is realted to getStats call.

**Comment by karthikbr82** [comment] 2019-04-09 08:12
@jossulli #45 is closed but we still see the error happening that is reported in this issue on chrome canary. Error what we see on console is.

lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:38975 Uncaught (in promise) TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': parameter 2 is not of type 'MediaStreamTrack'.
    at lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:38975
    at new Promise (<anonymous>)
    at RTCPeerConnection.pc.getStats (lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:38973)
    at RtcSession._callee$ (lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:42244)
    at tryCatch (lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:37351)
    at Generator.invoke [as _invoke] (lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:37585)
    at Generator.prototype.<computed> [as next] (lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:37403)
    at step (lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:35209)
    at lily_ccp_Prod_594a5767c26197c8d14035b02a8047c5baef2b17.gz.js:35227
    at new Promise (<anonymous>)


I think you should re-open this issue until this is resolved.

**Comment by yuliangz** [comment] 2019-04-09 21:56
Agreed. Latest release of 75 has fixed the DTLS issue but the getStats is still broken for connect-rtc-js. Reopening the issue.

**Comment by karthikbr82** [comment] 2019-04-10 12:58
@yuliangz @jossulli Now that you will be looking into getStats API, can you also make use the promise based getStats instead of callback-based one. The callback based getStats is deprecated and will be removed soon in both chrome and firefox.

https://github.com/aws/amazon-connect-streams/issues/80

**Comment by yiming-amzn** [comment] 2023-03-02 17:11
I think this issue is address as we supported both legacy and standardized getStats api in previous releases. Closing the issue

**Closed by yiming-amzn** 2023-03-02 17:11 UTC
